Repository PumpMyKins/PMK-OzoneUtils, pull requests merged in 2018-09, with the labels that each got.

#8 Feature/add money command
  .classpath
  plugin.yml
  src/fr/pmk_ozone/MainOzone.java
  src/fr/pmk_ozone/command/MoneyCommand.java
  src/fr/pmk_ozone/island/IslandManager.java
Labels: feature

#6 Feature/add erebus fonctionnality
  .classpath
  plugin.yml
  src/fr/pmk_ozone/MainOzone.java
  src/fr/pmk_ozone/erebus/ErebusManager.java
  src/fr/pmk_ozone/erebus/commands/ErebusBossCommand.java
  src/fr/pmk_ozone/erebus/commands/ErebusCommandExecutor.java
  src/fr/pmk_ozone/erebus/commands/ErebusHelpCommand.java
  src/fr/pmk_ozone/erebus/commands/ErebusMobsCommand.java
  src/fr/pmk_ozone/erebus/commands/ISubCommand.java
  src/fr/pmk_ozone/erebus/commands/SubData.java
Labels: feature

#9 Hotfix/fix erebus listener
  src/fr/pmk_ozone/erebus/commands/ErebusBossCommand.java
Labels: hotfix

#11 Update Feature/add money command
  src/fr/pmk_ozone/MainOzone.java
  src/fr/pmk_ozone/island/IslandManager.java
Labels: feature, update

#12 Feature/add starting stuff gui inventory
  plugin.yml
  src/fr/pmk_ozone/MainOzone.java
  src/fr/pmk_ozone/command/StartingStuffCommand.java
Labels: feature

#10 Feature/add subcmd reset island
  .settings/org.eclipse.core.resources.prefs
  src/fr/pmk_ozone/island/Island.java
  src/fr/pmk_ozone/island/IslandManager.java
  src/fr/pmk_ozone/island/commands/CResetIslandCmd.java
  src/fr/pmk_ozone/island/commands/ResetIslandCmd.java
Labels: feature
